bsl/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.urls import path
from django.http import HttpResponse
from django.conf import settings
from django.core.exceptions import PermissionDenied
from django.test import SimpleTestCase, override_settings
from django.conf.urls.static import static

from . import views


app_name = 'bsl'

urlpatterns = [
    path('', views.index, name='index'),
    path('login/', views.login_, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('register/', views.register, name='register'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('quiz/', views.showQuiz, name='quiz'),
    path('submitAnswer/<int:questionId>/<str:answer>', views.submitAnswer, name='submitAnswer'),
    path('stats/', views.stats, name='stats'),
    path('results/', views.results, name='results'),    
]

myapp/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('bsl/', include('bsl.urls')),
]

bsl/models.py
from django.db import models
from django.utils import timezone
from datetime import datetime


# Create your models here.

class user(models.Model):
    GENDER_CHOICES = (
        ('M','Male'),
        ('F','Female'),
    )
    id = models.IntegerField(primary_key=True)
    username = models.CharField(max_length=30)
    firstName = models.CharField(max_length=30)
    lastName = models.CharField(max_length=30)
    email = models.CharField(max_length=40)
    gender = models.CharField(max_length=2,choices=GENDER_CHOICES)
    profession = models.CharField(max_length=30)
    rating = models.IntegerField(default=1500)
    lower_bound = models.IntegerField(default=0)
    upper_bound = models.IntegerField(default=0)
    question_count = models.IntegerField(default=0)
    session_confidence = models.IntegerField(default=0)
    cSum = models.IntegerField(default=0)
    c_level_avg = models.IntegerField(default=0)
    score = models.IntegerField(default=0)

    def __str__(self):
        return self.username

class Question(models.Model):

    CATEGORY_CHOICES = (
        ('ECO','Economics'),
        ('HIS','History'),
        ('BAK','Banking'),
        ('GOV','Government'),
        ('PSY','Psycology'),
    )
    ANSWER_CHOICES = (
        ('A','A'),
        ('B','B'),
        ('C','C'),
        ('D','D'),
    )
    id = models.AutoField(primary_key=True)
    text = models.TextField()
    optionA = models.CharField(max_length=300)
    optionB = models.CharField(max_length=300)
    optionC = models.CharField(max_length=300)
    optionD = models.CharField(max_length=300)
    answer = models.CharField(max_length=1,choices=ANSWER_CHOICES)
    category = models.CharField(max_length=3,choices=CATEGORY_CHOICES)
    explanation = models.CharField(max_length=500,default="Lorem")
    rating = models.IntegerField(default=500)
    counter = models.IntegerField(default=0)
    ratingChange = models.IntegerField(default=0)


    def __str__(self):
        return self.text

class Attempt(models.Model):
    id = models.AutoField(primary_key=True)
    question = models.ForeignKey(Question,on_delete=models.CASCADE)
    userAtt = models.ForeignKey(user,on_delete=models.CASCADE)
    result = models.CharField(max_length=1,choices=(('C','Correct'),('W','Wrong')))
    clicks = models.IntegerField(default=1)
    time_diff = models.IntegerField(default=0)
    confidenceLevel = models.IntegerField(default=10)

class Stats(models.Model):
    userV = models.ForeignKey(user,on_delete=models.CASCADE)
    quizid = models.IntegerField(default=0)
    time = models.DateTimeField(default=timezone.now())
    score = models.IntegerField()

    def __str__(self):
        return self.userV.username+" "+str(self.quizid)

bsl/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse, Http404, HttpResponseRedirect
from django.contrib.auth.models import User
from django.utils.datastructures import MultiValueDictKeyError
from django.contrib.auth import authenticate, login, logout
from django.urls import reverse
from django.shortcuts import render_to_response
from django.template import RequestContext
from django.contrib.auth.models import User
import smtplib
import random



from .models import Question,user,Attempt,Stats
import matplotlib.pyplot as plt
# Create your views here.

def index(request):

    if request.user.is_authenticated:
        userId = User.objects.get(id=request.user.id)
        return HttpResponseRedirect(reverse('bsl:dashboard'))
    else:
        return render(request, 'bsl/index.html')

def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse('bsl:index'))

def login_(request):

    print("Login Request")
    if request.user.is_authenticated:
        return HttpResponseRedirect(reverse('bsl:dashboard'))

    try:
        log_in = request.POST['login']
    except MultiValueDictKeyError:
        return render(request, 'bsl/login.html')

    print("Login Post request")
    try:
        username = request.POST['username']
        password = request.POST['password']
    except MultiValueDictKeyError:
        error_message = "Missing Credentials"
        return HttpResponseRedirect(reverse('bsl:dashboard'))

    print("User getting auth")
    user = authenticate(request, username=username,password=password)
    if user is not None:
        login(request, user)
        print("login Successful")
        print (user.username)
        return HttpResponseRedirect(reverse('bsl:dashboard'))
    else:
        error_message = "Wrong Credentials"
        print("Login Failed")
        return render(request, 'bsl/login.html', {'error_message':error_message})

def register(request):

    errors = []
    #Check if the registeration button has been clicked
    try:
        new_registration = request.POST['register']
    except MultiValueDictKeyError:
        return render(request, 'bsl/register.html')

    try:
        username = request.POST['username']
        email = request.POST['email']
        password = request.POST['password_1']
        confirm_password = request.POST['password_2']
    except MultiValueDictKeyError:
        errors.append("Missing elements in form.")

    if len(errors)==0:
        if password!=confirm_password:
            errors.append("Passwords do not match.")
            registered = 'False'
        else:
            registered = register_user(username,email,password)
            #try to register user



    if len(errors)==0 and registered=='success':
            user = authenticate(request, username=username,password=password)
            login(request, user)
            return HttpResponseRedirect(reverse('bsl:fillProfile'))
    else:
        errors.append(registered)
        return render(request, 'bsl/register.html', {'error_message':errors})

def register_user(usr,mail,passcode):

    print("Trying to register user")
    try:
        test_username = User.objects.get(username=usr)
    except User.DoesNotExist:
        user = User.objects.create_user(usr, mail, passcode)
        user.save()
        return "success"

    return "Username is already registered"


def dashboard(request):
    userVar = user.objects.get(id=request.user.id)
    scoreVar = Stats.objects.filter(userV=userVar)

    return render(request,'bsl/dashboard.html',{'scores':scoreVar,'data':scoreVar})


def showQuiz(request):
    #Get some question from the database
    count = Question.objects.all().count()
    userVar = user.objects.get(id=request.user.id)
    rating = userVar.rating

    if(userVar.lower_bound==0):
        lower_bound = rating-50
        upper_bound = rating+150
        userVar.lower_bound = lower_bound
        userVar.upper_bound = upper_bound


    range_ = userVar.upper_bound - userVar.lower_bound
    range_ = range_/3
    lower_bound = userVar.lower_bound
    threshold = userVar.lower_bound + range_

    myQuestions = Question.objects.filter(rating__gt=lower_bound,rating__lt=threshold)
    print(str(lower_bound)+" : "+str(threshold))
    count = len(myQuestions)
    slice = (int(random.random()*(1000)))%count
    myQuestion = Question.objects.all()[slice: slice+1]
    userVar.save()
    #render pages
    return render(request, 'bsl/quiz.html', {'question':myQuestion[0]})

def submitAnswer(request,questionId,answer):
    print(request.POST['clicks'])
    print(request.POST['time_diff'])
    clicks = request.POST['clicks']
    time_diff = int(float(request.POST['time_diff']))
    td = int(time_diff)
    answer = request.POST.get('ans')
    questionVar = Question.objects.get(id=questionId)

    userVar = user.objects.get(id=request.user.id)
    c_level_avg = userVar.c_level_avg
    c_level = 0
    q_ratingChange = questionVar.ratingChange
    userVar.question_count = userVar.question_count+1
    questionVar.counter += 1
    userVar.save()
    questionVar.save()
    n = questionVar.counter
    i = userVar.question_count
    if(questionVar.answer==answer):
        result = 'C'
    else:
        result = 'W'

    if(result=='C'):
        userVar.score += 1
        nc = request.POST['clicks']
        nc = int(nc)
        l= userVar.lower_bound
        u = userVar.upper_bound


        q_rating = questionVar.rating
        q_ratingChange = questionVar.ratingChange

        bt = 0
        if q_rating <= l+66:
            bt = 5
        elif q_rating <= l+132:
            bt = 10
        else:
            bt = 20

        print(str(type(bt))+" : "+str(type(td)))
        print(td)
        if td <= bt:
            c1 = 1
        elif td>bt and td<2*bt:
            c1 = .6
        else:
            c1 = .3

        if nc == 1:
            c2 = 1
        elif nc == 2:
            c2 = .7
        elif nc == 3:
            c2 = .5
        else:
            c2 = .25

        c_level = ((2*c2)+c1)*100/3
        print("C LEVEL"+str(c_level))
        print("c1 and c2"+str(c1)+str(c2))

    else:
        c_level = -100

    userVar.cSum += c_level
    print("C LEVEL"+str(c_level))
    c_level_avg = ((c_level_avg*(i-1))+c_level)/i
    if(i%3==0):
        if(userVar.cSum<-40):
            if(userVar.lower_bound>70):
                userVar.lower_bound-=66
                userVar.upper_bound-=66
        elif(userVar.cSum>130):
            if(userVar.upper_bound<940):
                userVar.lower_bound+=66
                userVar.lower_bound+=66
        userVar.cSum = 0



    q_ratingChange = ((q_ratingChange*(n-1))+c_level)/n
    questionVar.q_ratingChange = q_ratingChange

    if n==5:
        if q_ratingChange<0:
            neg = -1
        else:
            neg = 1
        if q_ratingChange<=20:
            questionVar.rating = questionVar.rating+(neg*10)
        elif q_ratingChange<=40 and q_ratingChange>20:
            questionVar.rating = questionVar.rating+(neg*20)
        elif q_ratingChange<=60 and q_ratingChange>40:
            questionVar.rating = questionVar.rating+(neg*30)
        elif q_ratingChange<=80 and q_ratingChange>60:
            questionVar.rating = questionVar.rating+(neg*40)
        elif q_ratingChange>80:
            questionVar.rating = questionVar.rating+(neg*50)

        questionVar.q_ratingChange = 0
        questionVar.counter = 0
    print("Ic ounter" + str(i))
    if i==10:
        userVar.question_count = 0
        if c_level_avg<0:
          neg = -1
        else:
          neg = 1
        if c_level_avg<=20:
          userVar.rating = userVar.rating+(neg*20)
        elif c_level_avg<=40 and c_level_avg>20:
          userVar.rating = userVar.rating+(neg*40)
        elif c_level_avg<=60 and c_level_avg>40:
          userVar.rating = userVar.rating+(neg*60)
        elif c_level_avg<=80 and c_level_avg>60:
          userVar.rating = userVar.rating+(neg*80)
        elif c_level_avg>80:
          userVar.rating = userVar.rating+(neg*100)


        questionVar.save()
        userVar.save()
        print(answer+" correct is "+questionVar.answer)
        attempVar = Attempt(question=questionVar,userAtt=userVar,result=result,clicks=clicks,time_diff=time_diff)
        attempVar.save()

        myStat = Stats.objects.filter(userV=userVar).order_by('quizid')
        if(len(myStat)!=0):
            quizid = myStat[0].quizid + 1
        else:
            quizid = 1

        scoreVar = Stats(userV=userVar,quizid=quizid,score=userVar.score)
        myScore = userVar.score
        scoreVar.save()
        userVar.score = 0
        userVar.save()
        return render(request,"bsl/results.html",{'userVar':userVar,'scores':scoreVar,'myscore':myScore})

    questionVar.save()
    userVar.save()
    print(answer+" correct is "+questionVar.answer)
    attempVar = Attempt(question=questionVar,userAtt=userVar,result=result,clicks=clicks,time_diff=time_diff)
    attempVar.save()

    if(result=='C'):
        correctAnswer = "T"
        confi = c_level
    else:
        correctAnswer = "F"
        confi="None"

    print("Rendering feedback")
    print(questionVar.answer)
    if(answer=='A'):
        return render(request,'bsl/feedback.html',{'question':questionVar,'correctAnswer':correctAnswer,'optionA':"Checked",'confi':confi})
    if(answer=='B'):
        return render(request,'bsl/feedback.html',{'question':questionVar,'correctAnswer':correctAnswer,'optionB':"Checked",'confi':confi})
    if(answer=='C'):
        return render(request,'bsl/feedback.html',{'question':questionVar,'correctAnswer':correctAnswer,'optionC':"Checked",'confi':confi})
    if(answer=='D'):
        return render(request,'bsl/feedback.html',{'question':questionVar,'correctAnswer':correctAnswer,'optionD':"Checked",'confi':confi})



def results(request):
    return render(request,'bsl/results.html')


def stats(request):
    return

bsl/templates/bsl/dashboard.html
<!doctype html>
<html>
    <head>
        <meta charset="utf-8">
        <meta name="author" content="Yash Agrawal and Shivam Kalhans">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">
        <link rel="stylesheet" type="text/css" href="css/loginstyle.css">
        <link rel="shortcut icon" href="icon.png" />
        <title>
            LearnWell
        </title>

		<style>

			#buttons{
				margin-top: 100px;
			}
		</style>

		<script type="text/javascript">
            function relocate1(){
                location.href = "{%url 'bsl:stats'%}";
            }
            function relocate2(){
                location.href = "{%url 'bsl:quiz'%}";
            }

        </script>



    </head>
    <body class="text-center">


<script type="text/javascript" src="https://www.google.com/jsapi"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script type="text/javascript">
 google.load('visualization', '1.0', {'packages':['corechart']});
  google.setOnLoadCallback(drawChart);
   function drawChart() { var data = new google.visualization.DataTable();
      data.addColumn('string', 'Number');
      data.addColumn('number', 'Number/10');
       data.addRows( {{ data }} );
        var chart = new google.visualization.LineChart(document.getElementById('chart_div'));
         chart.draw(data, {width: 400, height: 240, title: "Numbers"}); }
          </script>


       <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
            <div class="container">
                <div class="navbar-header">
                    <a class="navbar-brand" href="{%url 'bsl:index' %}"><i class="fas fa-chalkboard-teacher"></i> LearnWell</a>
            	</div>
				 <div class="collapse navbar-collapse" id="navbarContent">

                <ul class="navbar-nav ml-auto nav-right">
                  <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                      <i class="fas fa-user-cog"></i> {{request.user.username}}
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                      <a class="dropdown-item" href="{% url 'bsl:logout' %}"><i class="fas fa-sign-out-alt"></i> Logout</a>
                    </div>
                  </li>
                </ul>
              </div>
            </div>
        </nav>

		<div id="buttons" class="container text-center">
			<button type="button" class="btn btn-outline-dark btn-lg" onclick="relocate2()"><i class="far fa-file-alt"></i> Attempt Quiz</button>
		</div>

    <div class='div-id' style="margin:auto;padding:10px;">
          {%for score in scores%}
            <p> Score in quiz {{score.quizid}} is {{score.score}} </p>
          {%endfor%}
        </div>
      <div class="chart_div">
      </div>


         <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

    </body>
</html>

bsl/templates/bsl/index.html
<!doctype html>
<html>
    <head>
       <meta charset="utf-8">
         <meta name="author" content="Enigma">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">
        <link rel="stylesheet" type="text/css" href="css/style.css">
        <link rel="shortcut icon" href="icon.png" />
        <title>
        	LearnWell
		</title>

		<style>
			#welcome{
                margin-top: 150px;
            }

			#buttons{
				margin-top: 50px;
			}
		</style>

		<script type="text/javascript">
            function relocate1(){
                location.href = "login.html";
            }
            function relocate2(){
                location.href = "signup.html";
            }

        </script>

    </head>

    <body>
        <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
            <div class="container">
                <div class="navbar-header">
                    <a class="navbar-brand" href="#"><i class="fas fa-chalkboard-teacher"></i> LearnWell </a>
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarContent" aria-controls="navbarContent" aria-expanded="false" aria-label="Toggle navigation">
                     <span class="navbar-toggler-icon"></span>
                    </button>
                </div>

				<div class="collapse navbar-collapse" id="navbarContent">
                <ul class="navbar-nav ml-auto nav-right">
                    <li class="nav-item"><a class="nav-link" href="{% url 'bsl:register' %}"><i class="fas fa-user-plus"></i> Signup</a></li>
                    <li class="nav-item"><a class="nav-link" href="{% url 'bsl:login' %}"><i class="fas fa-user"></i> Login</a></li>
                </ul>
              </div>

			</div>
        </nav>

		<div id="welcome" class="container text-center">
      {%load static%}
            <img src="{%static 'bsl/images/welcome.png'%}" class="rounded" alt="welcome" height="200" width="350">
        </div>

		<div id="buttons" class="container text-center">
			<a  href="{% url 'bsl:login' %}"><button type="button" class="btn btn-outline-dark btn-lg" onclick="relocate1()"><i class="fas fa-user"></i>  Login</button> </a>
			<a href="{% url 'bsl:register' %}"><button type="button" class="btn btn-outline-dark btn-lg" onclick="relocate2()"><i class="fas fa-user-plus"></i> SignUp</button>  </a>
		</div>






        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    </body>

</html>

bsl/templates/bsl/login.html
<!doctype html>
<html>
    <head>
        <meta charset="utf-8">
        <meta name="author" content="Yash Agrawal and Shivam Kalhans">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">
        <link rel="stylesheet" type="text/css" href="css/loginstyle.css">
        {%load static%}
        <title>
            LearnWell
        </title>

		<style type="text/css">
			html,
			body {
			  height: 100%;
			}

			body {
			  display: -ms-flexbox;
			  display: flex;
			  -ms-flex-align: center;
			  align-items: center;
			  padding-top: 40px;
			  padding-bottom: 40px;
			  background-color: #f5f5f5;
			}

			.form-signin {
			  width: 100%;
			  max-width: 330px;
			  padding: 15px;
			  margin: auto;
			}
			.form-signin .checkbox {
			  font-weight: 400;
			}
			.form-signin .form-control {
			  position: relative;
			  box-sizing: border-box;
			  height: auto;
			  padding: 10px;
			  font-size: 16px;
			}
			.form-signin .form-control:focus {
			  z-index: 2;
			}
			.form-signin input[type="email"] {
			  margin-bottom: -1px;
			  border-bottom-right-radius: 0;
			  border-bottom-left-radius: 0;
			}
			.form-signin input[type="password"] {
			  margin-bottom: 10px;
			  border-top-left-radius: 0;
			  border-top-right-radius: 0;
			}

		</style>


    </head>
    <body class="text-center">
      {%if error_message%}
        {{error_message}}
      {%endif%}
       <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
            <div class="container">
                <div class="navbar-header">
                    <a class="navbar-brand" href="{%url 'bsl:index' %}"><i class="fas fa-chalkboard-teacher"></i> LearnWell</a>
                </div>
                <ul class="navbar-nav ml-auto nav-right">
                    <li class="nav-item"><a class="nav-link" href="{% url 'bsl:register'}"><i class="fas fa-user-plus"></i> SignUp</a></li>
                </ul>
            </div>
        </nav>

        <form class="form-signin" method="post" action="{% url 'bsl:login' %}">
          {%csrf_token%}
            <img class="mb-4" src="{%static 'bsl/images/signin.png'%}" alt="signin" width="72" height="72">
            <h1 class="h3 mb-3 font-weight-normal">Please sign in</h1>
            <label for="username" class="sr-only">username</label>
            <input  id="username" class="form-control" name="username" placeholder="username" required autofocus>
            <label for="inputPassword" class="sr-only">Password</label>
            <input type="password" id="inputPassword" class="form-control" name="password" placeholder="Password" required>
<!--            <span id='message'></span>-->

            <button name='login' class="btn btn-lg btn-primary btn-block" id="login" type="submit">Sign in</button>

            <hr align="center">
            <p class="mt-2 mb-3 text-muted"> Don't have an Account? <a href="{% url 'bsl:register' %}">Create One</a></p>
        </form>
        <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    </body>
</html>

bsl/templates/bsl/quiz.html
{%extends 'base.html' %}


{%block head%}
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">
{%endblock%}

{% block body %}

        <script type="text/javascript">
            var start_time=Date.now();
        </script>


        <script type="text/javascript">



            clicks=0;

            function clicked(){
                var clickid=document.getElementById('clickid');
                   var time_diffid=document.getElementById('time_diffid');
                clicks+=1;
                console.log(clicks);
            }

            function submitted(){
                   var clickid=document.getElementById('clickid');
                   var time_diffid=document.getElementById('time_diffid');
                end_time=Date.now();
                diff=(end_time-start_time)/1000;

                clickid.value=clicks.toString();
                time_diffid.value=diff.toString();

            }


        </script>

                <form class="form-signin" method="post" action="{% url 'bsl:submitAnswer' question.id 'A' %}" style="max-width:50%">
                    {%csrf_token%}
                <h3>{{question.text}} :</h3><br>
                <p>
                    <label for="optionA">{{question.optionA}}</label>
                    <input type="radio" onclick="clicked()" name="ans" value="A">
                </p>
                <p>
                    <label for="optionB" >{{question.optionB}}</label>
                    <input type="radio" onclick="clicked()" name="ans" value="B">
                </p>
                <p>
                    <label for="optionC" >{{question.optionC}}</label>
                    <input type="radio" onclick="clicked()" name="ans" value="C">
                </p>
                <p>
                    <label for="optionD" >{{question.optionD}}</label>
                    <input type="radio" onclick="clicked()" name="ans" value="D">
                </p>

                <input type="text" name="clicks" id="clickid" value="" hidden="true">
                <input type="text" name="time_diff" id="time_diffid" value="" hidden="true">


                <div id="submit">
                    <button name='submit' onclick="submitted()" class="btn btn-lg btn-primary btn-block" id="submit_but" >Submit Answer</button>
                </div>
                </form>

        <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>


{%endblock%}